### ISSUE TITLE
Some refactoring I would like to work on

### ISSUE THREAD

**Issue by edennuriel** [hortonworks/cloudbreak-deployer#440]
- Use latest version of docker-compose, this should make it easier to run CB on K8S and will simplify the docker-compose file 
- Support osx native docker (Hyperkit)
- add cbd ssh/attach or similar... just so there is an easy way to get a shell prompt on any running container for debugging
- allow a developer mode where cbd will not force regenerate and allow to work with edits made to docker-compose file

**Comment by mhmxs** [comment]
Hi @edennuriel ,

Glad to hear you would like to contribute to the project. most of them are nice to have features. About the last one, we already have flag for it https://github.com/hortonworks/cloudbreak-deployer/blob/5f3ec88424ddbae953a8041b00947ea4c5c7a404/include/compose.bash#L174 .

**Comment by pdarvasi** [comment]
Hi @edennuriel. 

Do you have something to contribute according to your comment? Otherwise I would like to close this issue due to the lack of activity.
